---
- name: Get oh-my-fish installer
  get_url:
    url: https://get.oh-my.fish
    dest: /tmp/oh-my.fish
    mode: '0777'
  changed_when: false

- name: Install oh-my-fish
  shell: /tmp/oh-my.fish --noninteractive -y
  args:
    creates: ~/.config/fish/conf.d/omf.fish
    executable: /usr/bin/fish

- name: Remove oh-my-fish installer
  file:
    path: /tmp/oh-my.fish
    state: absent
  changed_when: false

- name: check git plugin install
  shell: grep 'abbr.*git' ~/.config/fish/fish_variables
  register: gitcheck
  ignore_errors: True
  changed_when: false

- name: Install git plugin
  become_method: su
  shell: omf install https://github.com/jhillyerd/plugin-git
  args:
    executable: /usr/bin/fish
  when: gitcheck is failed

- name: Copy dircolors
  copy:
    src: dircolors
    dest: ~/.config/

- name: Copy starship config
  copy:
    src: starship.toml
    dest: ~/.config/

# Separated root|users synchronize as module bugs when using become on the task: it copies always in user homedir
- name: Sync fish config files for cli (if user)
  synchronize:
    src: fish/cli/
    dest: ~/.config/fish
    recursive: yes
  when: ansible_user_id != 'root'
  tags: rsync

- name: Sync fish config files for cli (if root)
  synchronize:
    src: fish/cli/
    dest: /root/.config/fish
    recursive: yes
  when: ansible_user_id == 'root'
  tags: rsync

- name: Sync fish config files for desktop (if user)
  synchronize:
    src: fish/desktop/
    dest: ~/.config/fish
    recursive: yes
  when: ansible_user_id != 'root'
  tags: rsync
